version: 0.2

env:
  variables:
    CODEARTIFACT_DOMAIN: "pr-domain"
    CODEARTIFACT_REPO: "pr-repository"
    REGION: "ap-south-1"
    DOMAIN_OWNER: "337243655832"
    EC2_PUBLIC_IP: "3.110.130.25"
    EC2_USER: "ubuntu"
    PARAM_NAME: "praveen-ec2-key"
    PACKAGE_NAME: "my-python-ec2-app"

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install --upgrade pip
      - pip install build twine

  pre_build:
    commands:
      - aws codeartifact login --tool twine \
        --repository $CODEARTIFACT_REPO \
        --domain $CODEARTIFACT_DOMAIN \
        --domain-owner $DOMAIN_OWNER \
        --region $REGION

  build:
    commands:
      - python -m build

  post_build:
    commands:
      - export CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token \
          --domain $CODEARTIFACT_DOMAIN --domain-owner $DOMAIN_OWNER \
          --region $REGION --query authorizationToken --output text)

      - twine upload --repository-url https://$CODEARTIFACT_DOMAIN-$DOMAIN_OWNER.d.codeartifact.$REGION.amazonaws.com/pypi/$CODEARTIFACT_REPO/ \
        -u aws -p $CODEARTIFACT_AUTH_TOKEN dist/*

      - aws ssm get-parameter --name "$PARAM_NAME" --with-decryption --query Parameter.Value --output text > key.pem
      - chmod 400 key.pem

      - ssh -o StrictHostKeyChecking=no -i key.pem $EC2_USER@$EC2_PUBLIC_IP << 'EOF'
          sudo apt update
          sudo apt install -y python3-pip awscli
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token \
            --domain praveen-domain \
            --domain-owner $ACCOUNT_ID \
            --region ap-south-1 \
            --query authorizationToken --output text)
          pip install --upgrade pip
          pip install my-python-ec2-app --extra-index-url https://praveen-domain-$ACCOUNT_ID.d.codeartifact.ap-south-1.amazonaws.com/pypi/praveen-repo/simple/ \
            --extra-index-url https://pypi.org/simple
          myapp
        EOF
